import Foundation
import Darwin

/// Address ranges of CDNs and hosting platforms that serve many unrelated
/// sites from the same IPs (Cloudflare, Fastly, Vercel, CloudFront, AWS Global
/// Accelerator). A blocked site hosted there must not be IP-blocked: the same
/// addresses also serve thousands of other sites, which would stop loading for
/// the whole, uncancellable session. /etc/hosts still blocks the site by name.
///
/// The prefix list lives in SharedHostingRanges.swift, generated by
/// scripts/update-shared-hosting.py from the providers' published lists.
public enum SharedHosting {

    private struct Prefix {
        let bytes: [UInt8]
        let length: Int
    }

    private static let prefixes: [Prefix] = rangeStrings.compactMap(parse)

    /// True when `ip` belongs to a shared hosting or CDN range.
    public static func contains(_ ip: String) -> Bool {
        guard let address = bytes(of: ip) else { return false }
        return prefixes.contains { matches(address, $0) }
    }

    private static func parse(_ cidr: String) -> Prefix? {
        let parts = cidr.split(separator: "/")
        guard parts.count == 2, let length = Int(parts[1]),
              let address = bytes(of: String(parts[0])),
              (0...(address.count * 8)).contains(length) else { return nil }
        return Prefix(bytes: address, length: length)
    }

    private static func bytes(of ip: String) -> [UInt8]? {
        var v4 = in_addr()
        if inet_pton(AF_INET, ip, &v4) == 1 { return withUnsafeBytes(of: &v4) { Array($0) } }
        var v6 = in6_addr()
        if inet_pton(AF_INET6, ip, &v6) == 1 { return withUnsafeBytes(of: &v6) { Array($0) } }
        return nil
    }

    private static func matches(_ address: [UInt8], _ prefix: Prefix) -> Bool {
        guard address.count == prefix.bytes.count else { return false }
        let fullBytes = prefix.length / 8
        guard address[..<fullBytes] == prefix.bytes[..<fullBytes] else { return false }
        let remainingBits = prefix.length % 8
        guard remainingBits > 0 else { return true }
        let mask = UInt8(0xff) << (8 - remainingBits)
        return address[fullBytes] & mask == prefix.bytes[fullBytes] & mask
    }
}
