#!/usr/bin/env python3
"""Regenerate Sources/HarbourCore/SharedHostingRanges.swift.

Shared hosting and CDN address ranges serve many unrelated sites from the same
IPs. Harbour never IP-blocks addresses inside them (name-level blocking in
/etc/hosts still applies), because doing so would break unrelated sites.

Usage: python3 scripts/update-shared-hosting.py
"""
import datetime
import json
import pathlib
import urllib.request

OUT = pathlib.Path(__file__).resolve().parent.parent / "Sources/HarbourCore/SharedHostingRanges.swift"

# Vercel publishes no machine-readable list; these prefixes are its documented
# edge addresses, confirmed with whois (OrgName: Vercel, Inc).
VERCEL = [
    "76.76.21.0/24", "216.150.1.0/24", "216.150.16.0/24", "216.198.79.0/24",
    "198.169.1.0/24", "198.169.2.0/24", "66.33.60.0/24", "64.29.17.0/24",
]


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "harbour-update-shared-hosting/1.0"})
    with urllib.request.urlopen(request, timeout=30) as r:
        return r.read().decode()


def main():
    cloudflare = fetch("https://www.cloudflare.com/ips-v4").split() + fetch("https://www.cloudflare.com/ips-v6").split()
    fastly_json = json.loads(fetch("https://api.fastly.com/public-ip-list"))
    fastly = fastly_json["addresses"] + fastly_json.get("ipv6_addresses", [])
    aws = json.loads(fetch("https://ip-ranges.amazonaws.com/ip-ranges.json"))

    def aws_service(name):
        v4 = [p["ip_prefix"] for p in aws["prefixes"] if p["service"] == name]
        v6 = [p["ipv6_prefix"] for p in aws["ipv6_prefixes"] if p["service"] == name]
        return sorted(set(v4)) + sorted(set(v6))

    groups = [
        ("Cloudflare", "https://www.cloudflare.com/ips/", cloudflare),
        ("Fastly", "https://api.fastly.com/public-ip-list", fastly),
        ("Vercel", "whois-confirmed edge prefixes", VERCEL),
        ("Amazon CloudFront", "https://ip-ranges.amazonaws.com/ip-ranges.json", aws_service("CLOUDFRONT")),
        ("AWS Global Accelerator (Netlify, others)", "https://ip-ranges.amazonaws.com/ip-ranges.json",
         aws_service("GLOBALACCELERATOR")),
    ]

    lines = [
        "// Generated by scripts/update-shared-hosting.py on %s. Do not edit by hand." % datetime.date.today(),
        "",
        "extension SharedHosting {",
        "    /// CIDR prefixes of multi-tenant CDNs and hosting platforms.",
        "    static let rangeStrings: [String] = [",
    ]
    for name, source, prefixes in groups:
        lines.append("        // %s (%d prefixes, source: %s)" % (name, len(prefixes), source))
        for i in range(0, len(prefixes), 4):
            lines.append("        " + " ".join('"%s",' % p for p in prefixes[i:i + 4]))
    lines += ["    ]", "}", ""]
    OUT.write_text("\n".join(lines))
    print("Wrote %s (%d prefixes)" % (OUT, sum(len(g[2]) for g in groups)))


if __name__ == "__main__":
    main()
